# Builds a self-contained bundle for running the pi coding agent on an HPC
# login node (no Nix, no root, no ssh keys, password/OTP auth only).
#
# Everything is read from the *evaluated* home-manager config, so
# modules/pi.nix stays the single source of truth: `nix build
# .#pi-hpc-bundle` always mirrors the live setup, including the model tiers
# and thinking levels currently configured.
#
# Bundle layout (result/):
#   pi-agent/.pi/agent/...  config tree (dereferenced store paths), copied
#                           into $HOME on the HPC by setup.sh
#   bin/age                 static age binary for keys.age / pi-unlock (login
#                           nodes may lack age, and gpg -c needs a pinentry)
#   pi-hpc-rc.sh            shell rc: PATH, hardened env, pi-unlock, aliases
#   bundle-info.sh          machine-readable facts consumed by setup.sh
#   setup.sh                one-shot installer to run on the HPC
#   README.md               walkthrough
#
# Secrets are excluded by construction: auth.json and the *-key files are
# sops-nix templates, not home.file entries, so they never enter the bundle.
# On the HPC the API keys live passphrase-encrypted and are loaded into the
# shell environment on demand (pi-unlock), never plaintext at rest.
{ lib, pkgs, hmConfig }:

let
  cfg = hmConfig.config;

  # home.file entries under ~/.pi/agent.
  piFileNames = builtins.filter (n: lib.hasPrefix ".pi/" n) (builtins.attrNames cfg.home.file);

  # Skills that do not make sense on a headless HPC login node. browser-tools
  # needs a display (patched chromium via CDP) and carries the largest vendored
  # dependency (puppeteer), so it stays out of the bundle. Everything else is
  # included: vscode (`code -d` works in a VSCode/Cursor Remote terminal),
  # youtube-transcript, brave-search, vision (delegates to Gemini).
  excludedFileNames = [
    ".pi/agent/skills/pi-skills/browser-tools"
  ];
  selectedFileNames = builtins.filter (n: !(builtins.elem n excludedFileNames)) piFileNames;

  piFileSource = name:
    let f = cfg.home.file.${name};
    in if f.source != null then f.source else pkgs.writeText name f.text;

  # API keys required on the HPC, derived from the same options that drive the
  # sops entries in modules/pi.nix. pi reads them from environment variables
  # (docs/providers.md), so no plaintext auth.json is ever written on the HPC.
  keyVars = [ "DEEPSEEK_API_KEY" ]
    ++ lib.optional cfg.my.pi.vision.enable "GEMINI_API_KEY"
    ++ lib.optional cfg.my.pi.go.enable "OPENCODE_API_KEY"
    ++ lib.optional cfg.my.pi.extras.piSkills.braveSearch.enable "BRAVE_API_KEY";

  # Model presets: reuse the pi-* aliases rendered by modules/pi.nix for zsh
  # and re-emit them as POSIX aliases (same syntax) for the HPC shell.
  piAliases = lib.filterAttrs (name: _: lib.hasPrefix "pi-" name) cfg.programs.zsh.shellAliases;
  quote = lib.replaceStrings [ "'" ] [ "'\\''" ];

  bundleInfo = pkgs.writeText "bundle-info.sh" ''
    # Generated by the pi-hpc-bundle flake output - do not edit.
    DEFAULT_MODEL="${cfg.my.pi.model}"
    KEY_VARS="${lib.concatStringsSep " " keyVars}"
  '';

  # Static age for keys.age encryption / pi-unlock on hosts without age and
  # without a pinentry (gpg -c cannot prompt on headless login nodes).
  # Fetch the official release binary: nixpkgs' pkgs.age is dynamically
  # linked against the store's glibc (won't run on the HPC), and pkgsStatic.age
  # drags in the whole stage0 bootstrap toolchain. Upstream release builds are
  # statically linked (CGO_ENABLED=0).
  ageBinary = pkgs.fetchurl {
    url = "https://github.com/FiloSottile/age/releases/download/v1.3.1/age-v1.3.1-linux-amd64.tar.gz";
    sha256 = "0xqkypl2c3qcwcrn6h2666iv6iw2ynhp5lrkyfqzhv6xrc4rrimx";
  };

  # fd and rg: pi's built-in find/grep tools use them, downloading from GitHub
  # on first run unless PI_OFFLINE=1. Offline HPCs can't fetch, so ship the
  # same static release binaries (musl static-pie) and drop them into
  # ~/.pi/agent/bin - pi's own tools dir (getBinDir). Same versions pi's
  # tools-manager would resolve via the GitHub "latest" API (fd 10.2.0,
  # ripgrep 14.1.1).
  fdBinary = pkgs.fetchurl {
    url = "https://github.com/sharkdp/fd/releases/download/v10.2.0/fd-v10.2.0-x86_64-unknown-linux-musl.tar.gz";
    sha256 = "0cn9z4l0pwb90g296lxibv5ckdvk0sqf34i949f58946q9ga5gyr";
  };
  rgBinary = pkgs.fetchurl {
    url = "https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz";
    sha256 = "13jdmvp3g0zjiq9crxsi9daa5qjrd82khvy2nzymyikc3rsg5yac";
  };

  rcSh = pkgs.writeText "pi-hpc-rc.sh" ''
    # Generated by the pi-hpc-bundle flake output - do not edit.
    # Sourced from ~/.bashrc / ~/.zshrc on the HPC login node (setup.sh adds
    # the hook). Provides PATH, hardened env, pi-unlock, and the model presets
    # mirroring modules/pi.nix.

    export PATH="$HOME/opt/node/bin:$HOME/.local/bin:$PATH"
    # Silent, offline-friendly startup on the HPC (provider API calls are
    # unaffected; only update checks / telemetry are disabled).
    export PI_SKIP_VERSION_CHECK=1
    export PI_OFFLINE=1

    # Decrypt the API keys into this shell on demand. keys.age is
    # passphrase-encrypted; plaintext keys never touch the disk.
    pi-unlock() {
      local f="$HOME/.pi/keys.age"
      [ -f "$f" ] || { echo "pi-unlock: $f missing (create it via the bundle setup.sh)" >&2; return 1; }
      local decrypted
      if command -v age >/dev/null 2>&1; then
        decrypted="$(age -d "$f")" || { echo "pi-unlock: decryption failed (wrong passphrase?)" >&2; return 1; }
      elif command -v gpg >/dev/null 2>&1; then
        decrypted="$(gpg -d -q "$f" 2>/dev/null)" || { echo "pi-unlock: decryption failed (wrong passphrase?)" >&2; return 1; }
      else
        echo "pi-unlock: need 'age' or 'gpg' to decrypt $f" >&2
        return 1
      fi
      # Normalize stored lines: `export VAR=value`, `VAR=value`, or
      # `var: value` (older setups stored the latter when the paste echoed the
      # prompt's var names). Names are upcased and opencode_go_api_key is
      # aliased to OPENCODE_API_KEY - the env var pi actually reads.
      eval "$(printf '%s\n' "$decrypted" | sed -E \
        -e 's/\r$//' \
        -e 's/^[[:space:]]*export[[:space:]]+//' \
        -e 's/^opencode_go_api_key[[:space:]]*:[[:space:]]*/opencode_api_key=/' \
        -e 's/^opencode_go_api_key=/opencode_api_key=/' \
        -e 's/^([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*:[[:space:]]*/\1=/' \
        -e 's/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/export \U\1\E="\2"/' \
        | grep '^export ')"
    }

    # Drop the keys again when done on a shared box.
    pi-lock() {
      unset ${lib.concatStringsSep " " keyVars}
    }

    # Model presets (same commands as the pi-* zsh aliases on the WSL side).
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: value: "alias ${name}='${quote value}'") piAliases)}
  '';
in
pkgs.runCommand "pi-hpc-bundle" { } ''
  mkdir -p "$out/pi-agent"
  ${lib.concatStringsSep "\n" (map (name: ''
    mkdir -p "$out/pi-agent/${lib.dirOf name}"
    cp -rL ${piFileSource name} "$out/pi-agent/${name}"
  '') selectedFileNames)}
  cp ${bundleInfo} "$out/bundle-info.sh"
  cp ${rcSh} "$out/pi-hpc-rc.sh"
  cp ${../hpc/setup.sh} "$out/setup.sh"
  cp ${../hpc/README.md} "$out/README.md"
  chmod +x "$out/setup.sh"

  # Static age, fd, rg for keys.age / pi-unlock and pi's find/grep tools on
  # hosts without these binaries (gpg -c cannot prompt on headless nodes, and
  # offline pi skips its fd/rg downloads).
  mkdir -p "$out/bin"
  tar -xzf ${ageBinary} -C "$out/bin" --strip-components=1 age/age
  tar -xzf ${fdBinary} -C "$out/bin" --strip-components=1 fd-v10.2.0-x86_64-unknown-linux-musl/fd
  tar -xzf ${rgBinary} -C "$out/bin" --strip-components=1 ripgrep-14.1.1-x86_64-unknown-linux-musl/rg
  chmod 755 "$out/bin/"*
''
